### ISSUE TITLE
[BUG] <In the Dropdown section, contents are not perfectly aligned in the mobile view>

### ISSUE THREAD

**Issue by souvikjs01** [asyncapi/conference-website#345] opened 2024-07-12 13:01 UTC
### Describe the bug.

Dropdown icon does not showing, and 'All' is aligned in left side.

### Expected behavior

Dropdown icon should be shown, and the inner content of the button should be in the middle.

### Screenshots

![asyncapi](https://github.com/user-attachments/assets/ab53cdd2-3d0b-40a2-9e60-720db757b46b)

### How to Reproduce

1. I first did this
2. I then did this
3. And so on . . . 

### 🥦 Browser

Google Chrome

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by ashmit-coder** [comment] 2024-07-12 13:08
Hey @Mayaleeeee could provide some insight on weather it's a bug or design decision?

**Comment by souvikjs01** [comment] 2024-07-12 13:37
Actually, there is code conflicting in Dropdown component, which has written justify-center and at the same time justify-between, so do you want these elements to be in the center or both end according to your design?

**Comment by Mayaleeeee** [comment] 2024-07-12 13:50
> Hey @Mayaleeeee could provide some insight on weather it's a bug or design decision?

Thanks for the ping @ashmit-coder 

I'm still trying to understand what the issue is at @souvikjs01 because it's working perfectly here from my side.

https://github.com/user-attachments/assets/ce02845f-0d87-4539-8c26-5acf2a7629e7

Also, @ashmit-coder, we should change the colour of the drop-down icon, I can barely see it.

**Comment by souvikjs01** [comment] 2024-07-12 15:02
Hey @Mayaleeeee 
I did not notice the dropdown icon, the bg color are same, so i thought it should be in the center like the picture. 
Also "justify-center" that create confusion this to be in center. 

![as](https://github.com/user-attachments/assets/47b568c2-2940-4aeb-b503-0449247a44c0)

**Comment by shauryag2002** [comment] 2024-07-12 19:20
Hi, can I work on this?

**Comment by anuragnegi000** [comment] 2024-07-16 14:32
is this issue is already completed? if not please assign it to me

**Comment by AceTheCreator** [comment] 2024-07-22 10:32
@Mayaleeeee @souvikjs01 @ashmit-coder, what's the status of this discussion?

**Comment by ashmit-coder** [comment] 2024-07-22 11:13
> > Hey @Mayaleeeee could provide some insight on weather it's a bug or design decision?
> 
> Thanks for the ping @ashmit-coder
> 
> I'm still trying to understand what the issue is l @souvikjs01 because it's working perfectly here from my side.
> 
> Please listen to the recording below.
> 
>  XRecorder_Compressed_12072024_144645.mp4 
> Also, @ashmit-coder, we should change the colour of the drop-down icon, I can barely see it.

Hey @Mayaleeeee sorry for the late reply.

The colour feature is a good, point and I think this issue should resolve that.

About the back feature that you suggested, I dont think thats how we should approach it, we can discuss that in another issue in my opinion.

**Comment by ashmit-coder** [comment] 2024-07-22 11:14
> Hey @Mayaleeeee I did not notice the dropdown icon, the bg color are same, so i thought it should be in the center like the picture. Also "justify-center" that create confusion this to be in center.
> 
> ![as](https://private-user-images.githubusercontent.com/145583181/348306068-47b568c2-2940-4aeb-b503-0449247a44c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NDY3NDIsIm5iZiI6MTcyMTY0NjQ0MiwicGF0aCI6Ii8xNDU1ODMxODEvMzQ4MzA2MDY4LTQ3YjU2OGMyLTI5NDAtNGFlYi1iNTAzLTA0NDkyNDdhNDRjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxMTA3MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmMyZjRiYWRhZGFkMjUyMTdmZmU5MjAwMTJjNTIwN2ZlYmRkMTE1Y2NkYmY4MTQ4YzBlNGFlM2ZhNTkwOGFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HvVX1K0idTV1xU2e-yk_3PLnJLUyJcMTNe1mh6lP7fg)

Hey @Mayaleeeee do you think we should do this?

**Comment by Mayaleeeee** [comment] 2024-08-08 20:40
> > Hey @Mayaleeeee I did not notice the dropdown icon, the bg color are same, so i thought it should be in the center like the picture. Also "justify-center" that create confusion this to be in center.
> > 
> > ![as](https://private-user-images.githubusercontent.com/145583181/348306068-47b568c2-2940-4aeb-b503-0449247a44c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NDY3NDIsIm5iZiI6MTcyMTY0NjQ0MiwicGF0aCI6Ii8xNDU1ODMxODEvMzQ4MzA2MDY4LTQ3YjU2OGMyLTI5NDAtNGFlYi1iNTAzLTA0NDkyNDdhNDRjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxMTA3MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmMyZjRiYWRhZGFkMjUyMTdmZmU5MjAwMTJjNTIwN2ZlYmRkMTE1Y2NkYmY4MTQ4YzBlNGFlM2ZhNTkwOGFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HvVX1K0idTV1xU2e-yk_3PLnJLUyJcMTNe1mh6lP7fg)
> 
> Hey @Mayaleeeee do you think we should do this?

Hello @ashmit-coder , the screenshot below was the response I got when I tried viewing the image you attached to this message. 

![Screenshot_20240808_213746_Samsung Internet.jpg](https://github.com/user-attachments/assets/c01b01fc-fb9f-478b-a113-1562d7b9f0b5)

**Comment by ashmit-coder** [comment] 2024-08-09 04:52
> > > Hey @Mayaleeeee I did not notice the dropdown icon, the bg color are same, so i thought it should be in the center like the picture. Also "justify-center" that create confusion this to be in center.
> > > 
> > > ![as](https://private-user-images.githubusercontent.com/145583181/348306068-47b568c2-2940-4aeb-b503-0449247a44c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NDY3NDIsIm5iZiI6MTcyMTY0NjQ0MiwicGF0aCI6Ii8xNDU1ODMxODEvMzQ4MzA2MDY4LTQ3YjU2OGMyLTI5NDAtNGFlYi1iNTAzLTA0NDkyNDdhNDRjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxMTA3MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmMyZjRiYWRhZGFkMjUyMTdmZmU5MjAwMTJjNTIwN2ZlYmRkMTE1Y2NkYmY4MTQ4YzBlNGFlM2ZhNTkwOGFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HvVX1K0idTV1xU2e-yk_3PLnJLUyJcMTNe1mh6lP7fg)
> > 
> > Hey @Mayaleeeee do you think we should do this?
> 
> Hello @ashmit-coder , the screenshot below was the response I got when I tried viewing the image you attached to this message. 
> 
> ![Screenshot_20240808_213746_Samsung Internet.jpg](https://github.com/user-attachments/assets/c01b01fc-fb9f-478b-a113-1562d7b9f0b5)
> 
> 

Is this visible?
[![Screenshot_20240809_102154_GitHub.jpg](https://github.com/user-attachments/assets/12a15bf2-299f-4ea7-ba86-b2fb5b073ae1)

**Comment by Mayaleeeee** [comment] 2024-08-21 10:40
> > > > Hey @Mayaleeeee I did not notice the dropdown icon, the bg color are same, so i thought it should be in the center like the picture. Also "justify-center" that create confusion this to be in center.
> > > > ![as](https://private-user-images.githubusercontent.com/145583181/348306068-47b568c2-2940-4aeb-b503-0449247a44c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NDY3NDIsIm5iZiI6MTcyMTY0NjQ0MiwicGF0aCI6Ii8xNDU1ODMxODEvMzQ4MzA2MDY4LTQ3YjU2OGMyLTI5NDAtNGFlYi1iNTAzLTA0NDkyNDdhNDRjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxMTA3MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmMyZjRiYWRhZGFkMjUyMTdmZmU5MjAwMTJjNTIwN2ZlYmRkMTE1Y2NkYmY4MTQ4YzBlNGFlM2ZhNTkwOGFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HvVX1K0idTV1xU2e-yk_3PLnJLUyJcMTNe1mh6lP7fg)
> > > 
> > > 
> > > Hey @Mayaleeeee do you think we should do this?
> > 
> > 
> > Hello @ashmit-coder , the screenshot below was the response I got when I tried viewing the image you attached to this message.
> > ![Screenshot_20240808_213746_Samsung Internet.jpg](https://private-user-images.githubusercontent.com/105395613/356372995-c01b01fc-fb9f-478b-a113-1562d7b9f0b5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzY5NjEsIm5iZiI6MTcyNDIzNjY2MSwicGF0aCI6Ii8xMDUzOTU2MTMvMzU2MzcyOTk1LWMwMWIwMWZjLWZiOWYtNDc4Yi1hMTEzLTE1NjJkN2I5ZjBiNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxMDM3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MGNiN2JjODc2MDdkZDNjNTUyOGVjODJmNzUxNWYzOTM1ZWM3MjIxMDU5MjUyZDIyYzdmNjNmOWE1YzhmMzJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PBb4QUmpj-E2KuEIB1NqCx1NwGN2MXj2Khw4Z93XMEo)
> 
> Is this visible? [![Screenshot_20240809_102154_GitHub.jpg](https://private-user-images.githubusercontent.com/69006513/356466686-12a15bf2-299f-4ea7-ba86-b2fb5b073ae1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzY5NjEsIm5iZiI6MTcyNDIzNjY2MSwicGF0aCI6Ii82OTAwNjUxMy8zNTY0NjY2ODYtMTJhMTViZjItMjk5Zi00ZWE3LWJhODYtYjJmYjViMDczYWUxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDEwMzc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZDZiZDc5N2IwOTY1MzFiNjA3MWUzYWE4ZTc4NjVjNTRmODM1ZmE0YWY4NGMzNTNhNjgwODk0NGM1ZDcxN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i6b42roxtHFoNeBEm2BpYob4HEkhH5EbFzjFPzxlwQU)

Do you mean the icon?

**Comment by ashmit-coder** [comment] 2024-08-21 11:39
> > > > > Hey @Mayaleeeee I did not notice the dropdown icon, the bg color are same, so i thought it should be in the center like the picture. Also "justify-center" that create confusion this to be in center.
> > > > > ![as](https://private-user-images.githubusercontent.com/145583181/348306068-47b568c2-2940-4aeb-b503-0449247a44c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NDY3NDIsIm5iZiI6MTcyMTY0NjQ0MiwicGF0aCI6Ii8xNDU1ODMxODEvMzQ4MzA2MDY4LTQ3YjU2OGMyLTI5NDAtNGFlYi1iNTAzLTA0NDkyNDdhNDRjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxMTA3MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmMyZjRiYWRhZGFkMjUyMTdmZmU5MjAwMTJjNTIwN2ZlYmRkMTE1Y2NkYmY4MTQ4YzBlNGFlM2ZhNTkwOGFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HvVX1K0idTV1xU2e-yk_3PLnJLUyJcMTNe1mh6lP7fg)
> > > > 
> > > > 
> > > > Hey @Mayaleeeee do you think we should do this?
> > > 
> > > 
> > > Hello @ashmit-coder , the screenshot below was the response I got when I tried viewing the image you attached to this message.
> > > ![Screenshot_20240808_213746_Samsung Internet.jpg](https://private-user-images.githubusercontent.com/105395613/356372995-c01b01fc-fb9f-478b-a113-1562d7b9f0b5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzY5NjEsIm5iZiI6MTcyNDIzNjY2MSwicGF0aCI6Ii8xMDUzOTU2MTMvMzU2MzcyOTk1LWMwMWIwMWZjLWZiOWYtNDc4Yi1hMTEzLTE1NjJkN2I5ZjBiNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxMDM3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MGNiN2JjODc2MDdkZDNjNTUyOGVjODJmNzUxNWYzOTM1ZWM3MjIxMDU5MjUyZDIyYzdmNjNmOWE1YzhmMzJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PBb4QUmpj-E2KuEIB1NqCx1NwGN2MXj2Khw4Z93XMEo)
> > 
> > Is this visible? [![Screenshot_20240809_102154_GitHub.jpg](https://private-user-images.githubusercontent.com/69006513/356466686-12a15bf2-299f-4ea7-ba86-b2fb5b073ae1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzY5NjEsIm5iZiI6MTcyNDIzNjY2MSwicGF0aCI6Ii82OTAwNjUxMy8zNTY0NjY2ODYtMTJhMTViZjItMjk5Zi00ZWE3LWJhODYtYjJmYjViMDczYWUxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDEwMzc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZDZiZDc5N2IwOTY1MzFiNjA3MWUzYWE4ZTc4NjVjNTRmODM1ZmE0YWY4NGMzNTNhNjgwODk0NGM1ZDcxN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i6b42roxtHFoNeBEm2BpYob4HEkhH5EbFzjFPzxlwQU)
> 
> Do you mean the icon? @ashmit-coder 

No the text in the buttons. Shall we make it center aligned rather than the existing left aligned

**Comment by Mayaleeeee** [comment] 2024-08-21 12:20
> > > > > > Hey @Mayaleeeee I did not notice the dropdown icon, the bg color are same, so i thought it should be in the center like the picture. Also "justify-center" that create confusion this to be in center.
> > > > > > ![as](https://private-user-images.githubusercontent.com/145583181/348306068-47b568c2-2940-4aeb-b503-0449247a44c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NDY3NDIsIm5iZiI6MTcyMTY0NjQ0MiwicGF0aCI6Ii8xNDU1ODMxODEvMzQ4MzA2MDY4LTQ3YjU2OGMyLTI5NDAtNGFlYi1iNTAzLTA0NDkyNDdhNDRjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxMTA3MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmMyZjRiYWRhZGFkMjUyMTdmZmU5MjAwMTJjNTIwN2ZlYmRkMTE1Y2NkYmY4MTQ4YzBlNGFlM2ZhNTkwOGFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HvVX1K0idTV1xU2e-yk_3PLnJLUyJcMTNe1mh6lP7fg)
> > > > > 
> > > > > 
> > > > > Hey @Mayaleeeee do you think we should do this?
> > > > 
> > > > 
> > > > Hello @ashmit-coder , the screenshot below was the response I got when I tried viewing the image you attached to this message.
> > > > ![Screenshot_20240808_213746_Samsung Internet.jpg](https://private-user-images.githubusercontent.com/105395613/356372995-c01b01fc-fb9f-478b-a113-1562d7b9f0b5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzY5NjEsIm5iZiI6MTcyNDIzNjY2MSwicGF0aCI6Ii8xMDUzOTU2MTMvMzU2MzcyOTk1LWMwMWIwMWZjLWZiOWYtNDc4Yi1hMTEzLTE1NjJkN2I5ZjBiNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxMDM3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MGNiN2JjODc2MDdkZDNjNTUyOGVjODJmNzUxNWYzOTM1ZWM3MjIxMDU5MjUyZDIyYzdmNjNmOWE1YzhmMzJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PBb4QUmpj-E2KuEIB1NqCx1NwGN2MXj2Khw4Z93XMEo)
> > > 
> > > 
> > > Is this visible? [![Screenshot_20240809_102154_GitHub.jpg](https://private-user-images.githubusercontent.com/69006513/356466686-12a15bf2-299f-4ea7-ba86-b2fb5b073ae1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzY5NjEsIm5iZiI6MTcyNDIzNjY2MSwicGF0aCI6Ii82OTAwNjUxMy8zNTY0NjY2ODYtMTJhMTViZjItMjk5Zi00ZWE3LWJhODYtYjJmYjViMDczYWUxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDEwMzc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZDZiZDc5N2IwOTY1MzFiNjA3MWUzYWE4ZTc4NjVjNTRmODM1ZmE0YWY4NGMzNTNhNjgwODk0NGM1ZDcxN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i6b42roxtHFoNeBEm2BpYob4HEkhH5EbFzjFPzxlwQU)
> > 
> > 
> > Do you mean the icon? @ashmit-coder
> 
> No the text in the buttons. Shall we make it center aligned rather than the existing left aligned

Yes, please.

The centre looks good. @ashmit-coder

**Comment by souvikjs01** [comment] 2024-08-21 17:37
@ashmit-coder  @Mayaleeeee 
Can I work on it?? If so, please assign it to me.

**Comment by ashmit-coder** [comment] 2024-08-21 17:39
> @ashmit-coder  @Mayaleeeee 
> Can I work on it?? If so, please assign it to me.

You can start working no need to be assigned!

**Closed as completed** 2024-10-30 11:04 UTC
Labels: bug, Hacktoberfest
